### ISSUE TITLE
Fix buttons in DatasetHeader

### ISSUE THREAD

**Issue by cpvannier** [pixano/pixano#119]
- Back button currently behaves exactly like the Pixano logo and takes the user to the home page regardless of the current page. It should instead go back to the parent page (home page if on dataset, dataset page if on item)
- Missing tooltips for back button and dataset navigation buttons

**Comment by BertrandRenault** [comment]
Also, I noticed the Pixano icon doesn't check for unsaved changes

**Comment by cpvannier** [comment]
That's true. I'll try adding the ConfirmModal for those buttons in the same PR.

**Comment by cpvannier** [comment]
Actually created a separate issue: #125
