### ISSUE TITLE
Error when using COCOExporter to export a dataset

### ISSUE THREAD

**Issue by alexsetkov** [pixano/pixano#201]
## Bug description
I get an error when using COCOExporter to export a dataset.
![image](https://github.com/pixano/pixano/assets/4668770/78a4817b-4818-4ae9-b8a0-5edf79e22b00)

## Steps to reproduce
exporter = COCOExporter(input_dir)
exporter.export_dataset(export_dir, copy=True)

**Comment by cpvannier** [comment]
Thanks for the report!

Looks like the error is happening because we don't except the "categories" to be None, so we try iterating on it without checking it first. The fix for this should be able to make it in the 0.5.0 release.
