### ISSUE TITLE
Getting a blank page whether I launch the application via Jupyter Notebook or directly from the command line

### ISSUE THREAD

**Issue by CecileFiche** [pixano/pixano#225]
Launching `app = App(directory_path)` gives no error : GET requests gives a 200 status. So the application seems to work correctly. But `localhost:8000` corresponds to a blanck page. Nothing is displayed. 

I'm using the latest up-to-date version of the Pixano application (v0.5.1) and pixano-inference (0.3.1) to annotate data based on SAM. Everything works fine (calculating masks and embeddings as well as creating the database) until the step of launching the application. When I navigate to port 8000, I don't see any apparent errors, just a blank page. However, all routes seems to work correctly. Upon closer inspection, I notice that some JS files cannot be downloaded (I've checked, I have them locally), and therefore the script located in the app's index.html that displays the datasets, etc., does not execute. I'm using Chrome, but I have the same problem on Edge. I can't test it on Firefox. Here are the errors I'm getting:

`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module : http://0.0.0.1:8000/_app/immutable/entry/start.XXXX.js`

`Failed to load module script: Expected a Javascript module script but the server responded start.XXX.js with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

(I got similar error for the others JS files)

I replaced the dynamical name of the JS file by XXXX for simplicity but i confirm it is not xxxx. 

Do you have any ideas to solve this problem ? Thank you !

**Comment by BertrandRenault** [comment]
This issue was most probably linked to some not up-to-date packages error. 
Several libs have been upgraded in 0.6, and this issue seems resolved.

fixed with 0.6
