### ISSUE TITLE
Slow backup when saving annotations

### ISSUE THREAD

**Issue by MattPaques** [pixano/pixano#234]
## Bug description

I have a dataset with 144 images of size (1568,1568), 20 classes and ~50 segmentation annotations per image. It takes ~ 7 min every time I press the button "save changes" or if I try to change the image displayed and I press "save changes then continue".

## Steps to reproduce

1. Installed pixano version 050, python 3.10
2. Dataset with large images (1568,1568), dozens of segmentation annotations per image.
3. Click 'save changes' after having annotated the image.

## Expected behavior

Screen is gray with charging circle for 7 min.

**Comment by ulysse-bonneau** [comment]
After studying the issue, we have determined that it's caused by the add_or_update function (pixano/data/item/item_object.py). We will now be working on a fix.

**Comment by BertrandRenault** [comment]
"Save" is wrongly updating data for each existing object. 
We need either to flag changed objects to update them only, or update everythin in one go.

**Comment by MattPaques** [comment]
Thanks Bertrand! Congrats to the Pixano team that's a great tool !

**Comment by BertrandRenault** [comment]
The fix will be released in version 0.5.2 that will be available next week

**Comment by BertrandRenault** [comment]
release 0.5.2 is now available

Thanks for using our product @MattPaques
