### ISSUE TITLE
Improve video player layout

### ISSUE THREAD

**Issue by timothee-LJN** [pixano/pixano#244]
## Feature description

- [x] object track should be full size 
- [x] player should be displayed outside video track
- [x] box thumbnail should be displayed
- [x] box freshly created should be displayed in video object inspector 
- [x] edition tool should be automatically selected when changing time
- [x] show thumbnail in scene editor
- [x] video inspector size is draggeable

**Comment by BertrandRenault** [comment]
closed with #248 #253 and #258
