### ISSUE TITLE
Various front bugs list

### ISSUE THREAD

**Issue by BertrandRenault** [pixano/pixano#267]
## Bug description
A list of several bugs in current "python_refactor" version
More important bugs could be moved in a separate issue

- [x] With a video dataset, when we change datasetItem with header arrows, the current frame position is kept. If the new datasetItem has fewer frame than current position, we have a bug

- [x] When a big bbox is selected, the list of object is not reachable anymore (no scrollbar, too much blank space)
![image](https://github.com/pixano/pixano/assets/112549869/e63f9846-1b46-47fa-8487-2f831a58777b)

- [x] Thumbnail in the upper right panel is not centered horizontally
![image](https://github.com/pixano/pixano/assets/112549869/1985f8f5-196f-4afa-8b18-d3703a8e95cf)

Note: moved some issues on separate issues

**Comment by timothee-LJN** [comment]
>  On refresh (F5), sometimes the image/frame is not centered 

any chance you could provide me with more details please? I cannot reproduce: every time I refresh, the frame is correctly centered. Maybe you changed your window size after refreshing?

**Comment by timothee-LJN** [comment]
Bug fixes can be tested here : https://github.com/pixano/pixano/pull/268

**Comment by BertrandRenault** [comment]
> > On refresh (F5), sometimes the image/frame is not centered
> 
> any chance you could provide me with more details please? I cannot reproduce: every time I refresh, the frame is correctly centered. Maybe you changed your window size after refreshing?

It's not consistent, and could appears randomly. But usually if you keep refreshing, after some tries the issue arise. No manual resizing, only refresh (f5) of the browser.

**Comment by BertrandRenault** [comment]
closed with #268
