### ISSUE TITLE
Disable anti-aliasing (image smoothing) on the canvas

### ISSUE THREAD

**Issue by leMarchandeSable** [pixano/pixano#277]
## Feature description

Disable anti-aliasing (image smoothing) on the canvas to improve the accuracy of visual representation in the Pixano annotation tool. Particularly for tasks that require precise pixel-level annotations.

## Expected solution

Add a configuration option to the python App.display() function to disable image smoothing on the canvas element. This can be implemented by setting the `imageSmoothingEnabled` property to `false` when the canvas context is initialized.

This setting should be applied globally to all canvas elements used in the application, ensuring that images are displayed with or without smoothing by default.

## Additional context

Currently, users need to manually disable image smoothing for each image, with this command on developper console: `$("canvas").getContext("2d").imageSmoothingEnabled = false `. Implementing this feature will ensure that all images are displayed with or without anti-aliasing, maintaining the integrity of pixel data for accurate annotations.

Here is a screenshot demonstrating the difference between smoothed and non-smoothed images:

**1. image with antialiasing**
![image with pixano antialiasing](https://github.com/pixano/pixano/assets/95425179/36c82ec2-4d24-4b1a-8bef-109b1cfb6871)

**2. image without antialiasing**
![image without pixano antialiasing](https://github.com/pixano/pixano/assets/95425179/8d8f8cf1-ba04-42c4-87cd-53ab2b194a51)

**Comment by BertrandRenault** [comment]
Hello @leMarchandeSable 
The option to enable/disable anti-aliasing has been added, in Scene tab
It will be released very soon (today probably) in pixano 0.5.4

**Comment by ulysse-bonneau** [comment]
We added a toggle to turn it off/on in v0.5.4. It can be found in the scene tab on the right.
![image](https://github.com/pixano/pixano/assets/50866369/bb59543a-e0cf-49dd-96c9-a47e5efd4a7c)
