### ISSUE TITLE
Pixano no longer works with pixano-inference

### ISSUE THREAD

**Issue by CecileFiche** [pixano/pixano#348]
**First**: 
The version of numpy must be downgraded to be able to import Pixano **`ImageImporter`** class.
`from pixano.data import ImageImporter` gives the error :  `ImportError: numpy.core.multiarray failed to import`
So I had to downgrade to `numpy==1.24` to make it work.

 **Second**: 
pixano does not work with pixano-inference. Multiple conflicts at the installation, particularly at the torch level. Pixano-inference forces the installation of a version of torch that is too old which makes the use of cuda impossible and therefore no longer allows a SAM model to be loaded since it requires a GPU.

**Comment by BertrandRenault** [comment]
New way to compute embeddings.
pixano-inference is not used anymore in pixano 0.6+

fixed in pixano 0.6+
