### ISSUE TITLE
Remove interactive segmentation prompts once the mask is created

### ISSUE THREAD

**Issue by jrabary** [pixano/pixano#88]
<img width="468" alt="Capture d’écran 2024-02-02 à 15 29 06" src="https://github.com/pixano/pixano/assets/1025387/1560fd39-71fd-4e9e-8c4b-a48375e7ef39">

**Comment by timothee-LJN** [comment]
to clean all inputs: `clearAnnotationAndInputs`
to clean only constructions inputs : `clearInputs`
