### ISSUE TITLE
Create bbox from mask and display it after saving

### ISSUE THREAD

**Issue by timothee-LJN** [pixano/pixano#89]
- [x] Stop displaying an empty bounding box before it's created from a mask or polygon (#92)
- [ ] Display the bounding box created from the mask or polygon as soon as the item is saved (#131)

**Comment by timothee-LJN** [comment]
@cpvannier do you think we could improve that workflow? Either the box could be created directly once the mask is created (client side) or at least we could avoid sending an empty box?

**Comment by cpvannier** [comment]
@timothee-LJN

#92 fixes the issue of creating the bounding box automatically in the backend API and removes the need for an empty box in the frontend.

However, for the second point (displaying the bounding box as soon as the item is saved), to me the only option is to run a GET after the POST to retrieve the saved objects including that new bounding box. I feel like this is a good thing to do anyway to make sure that we are displaying what is actually stored in the database after a save. What do you think?

**Comment by timothee-LJN** [comment]
ok I'll try to do that. The main reason why I removed the get after the post was to save some time and improve UX. If the currentItem is heavy, it can add few seconds. What about sending the updated item in the response of the  POST ?

**Comment by cpvannier** [comment]
That could work, but the POST response would have to use the same API as the GET to retrieve the actual item as it is stored, so I don't know if it would save much time compared to calling the GET directly from the frontend.
